services:
  web:
    image: erichard56/hunglin4-web:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hunglin
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/web
    ports:
      - "8001:8000"
  service_name:
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64


