# Generated by Django 5.0.7 on 2024-08-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificado/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
