# Generated by Django 5.0.7 on 2024-08-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0028_persona_foto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='foto2',
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
