# Generated by Django 5.0.7 on 2024-08-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0029_remove_persona_foto2_alter_persona_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='foto',
            new_name='foto2',
        ),
    ]
