# Generated by Django 5.0.7 on 2024-08-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0030_rename_foto_persona_foto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
